export const CoreEventType = {
  TENANT_CREATED: 'CORE.TENANT_CREATED',
  MEMBERSHIP_CREATED: 'CORE.MEMBERSHIP_CREATED',
  MEMBERSHIP_ROLE_UPDATED: 'CORE.MEMBERSHIP_ROLE_UPDATED',
  MEMBERSHIP_STATUS_UPDATED: 'CORE.MEMBERSHIP_STATUS_UPDATED',
  UNIT_CREATED: 'CORE.UNIT_CREATED',
  UNIT_UPDATED: 'CORE.UNIT_UPDATED',
  UNIT_DELETED: 'CORE.UNIT_DELETED',
  OWNER_CREATED: 'CORE.OWNER_CREATED',
  OWNER_DELETED: 'CORE.OWNER_DELETED',
  UNIT_OWNERSHIP_REPLACED: 'CORE.UNIT_OWNERSHIP_REPLACED',
  UNIT_OWNERSHIP_TRANSFER_CANCELLED: 'CORE.UNIT_OWNERSHIP_TRANSFER_CANCELLED',
  OWNER_USER_LINKED: 'CORE.OWNER_USER_LINKED',
  OWNER_USER_UNLINKED: 'CORE.OWNER_USER_UNLINKED',
  OWNER_EMAIL_ADDED: 'CORE.OWNER_EMAIL_ADDED',
  OWNER_RENAMED: 'CORE.OWNER_RENAMED',
  OWNERSHIP_PERIOD_UPDATED: 'CORE.OWNERSHIP_PERIOD_UPDATED',
  OWNER_INVITE_SENT: 'CORE.OWNER_INVITE_SENT',
  OWNER_INVITE_REVOKED: 'CORE.OWNER_INVITE_REVOKED',
  OWNER_INVITE_ACCEPTED: 'CORE.OWNER_INVITE_ACCEPTED',
  KATASTR_DATA_IMPORTED: 'CORE.KATASTR_DATA_IMPORTED',
} as const;

export type CoreEventType = (typeof CoreEventType)[keyof typeof CoreEventType];
