import { createContext, ReactNode, useContext, useState } from "react";

// TODO: Replace with real autogenerated User type when backend auth is done
interface User {
    id: string;
    email: string;
    role: "ADMIN" | "BOARD_MEMBER" | "RESIDENT";
}

interface AuthContextType {
    user: User | null;
    isAuthenticated: boolean;
    isLoading: boolean;
    login: (token: string, user: User) => void;
    logout: () => void;
}

const AuthContext = createContext<AuthContextType | null>(null);

function getInitialUser(): User | null {
    const token = localStorage.getItem("auth_token");
    const storedUser = localStorage.getItem("auth_user");

    if (token && storedUser) {
        try {
            return JSON.parse(storedUser);
        } catch {
            localStorage.removeItem("auth_token");
            localStorage.removeItem("auth_user");
        }
    }
    return null;
}

export function AuthProvider({ children }: { children: ReactNode }) {
    const [user, setUser] = useState<User | null>(getInitialUser);

    const login = (token: string, userData: User) => {
        localStorage.setItem("auth_token", token);
        localStorage.setItem("auth_user", JSON.stringify(userData));
        setUser(userData);
    };

    const logout = () => {
        localStorage.removeItem("auth_token");
        localStorage.removeItem("auth_user");
        setUser(null);
    };

    return (
        <AuthContext.Provider
            value={{
                user,
                isAuthenticated: !!user,
                isLoading: false, // LocalStorage is sync, so we are never truly loading here
                login,
                logout,
            }}
        >
            {children}
        </AuthContext.Provider>
    );
}

export function useAuth() {
    const context = useContext(AuthContext);
    if (!context) {
        throw new Error("useAuth must be used within an AuthProvider");
    }
    return context;
}
