export const VotingEventType = {
  VOTE_CREATED: 'VOTING.VOTE_CREATED',
  VOTE_UPDATED: 'VOTING.VOTE_UPDATED',
  VOTE_DELETED: 'VOTING.VOTE_DELETED',
  VOTE_RULESET_SET: 'VOTING.VOTE_RULESET_SET',
  VOTE_RULESET_NON_STATUTORY_ACKNOWLEDGED:
    'VOTING.VOTE_RULESET_NON_STATUTORY_ACKNOWLEDGED',
  VOTE_SCHEDULED: 'VOTING.VOTE_SCHEDULED',
  VOTE_OPENED: 'VOTING.VOTE_OPENED',
  VOTE_ELECTORATE_SNAPSHOTTED: 'VOTING.VOTE_ELECTORATE_SNAPSHOTTED',
  VOTE_QUESTION_CREATED: 'VOTING.VOTE_QUESTION_CREATED',
  VOTE_QUESTION_UPDATED: 'VOTING.VOTE_QUESTION_UPDATED',
  VOTE_QUESTION_DELETED: 'VOTING.VOTE_QUESTION_DELETED',
  VOTE_CONSENT_CREATED: 'VOTING.VOTE_CONSENT_CREATED',
  VOTE_CONSENT_REVOKED: 'VOTING.VOTE_CONSENT_REVOKED',
  BALLOT_CAST_DIRECT: 'VOTING.BALLOT_CAST_DIRECT',
  BALLOT_CAST_PROXY: 'VOTING.BALLOT_CAST_PROXY',
  VOTE_CLOSED: 'VOTING.VOTE_CLOSED',
  VOTE_RESULTS_COMPUTED: 'VOTING.VOTE_RESULTS_COMPUTED',
  VOTE_DOCUMENT_ADDED: 'VOTING.VOTE_DOCUMENT_ADDED',
  VOTE_DOCUMENT_REMOVED: 'VOTING.VOTE_DOCUMENT_REMOVED',
  ASSEMBLY_ATTENDANCE_RECORDED: 'VOTING.ASSEMBLY_ATTENDANCE_RECORDED',
  ASSEMBLY_RECORD_PUBLISHED: 'VOTING.ASSEMBLY_RECORD_PUBLISHED',
} as const;

export type VotingEventType =
  (typeof VotingEventType)[keyof typeof VotingEventType];
