export const VotingEventType = {
  VOTE_CREATED: 'VOTING.VOTE_CREATED',
  VOTE_RULESET_SET: 'VOTING.VOTE_RULESET_SET',
  VOTE_SCHEDULED: 'VOTING.VOTE_SCHEDULED',
  VOTE_OPENED: 'VOTING.VOTE_OPENED',
  VOTE_ELECTORATE_SNAPSHOTTED: 'VOTING.VOTE_ELECTORATE_SNAPSHOTTED',
  BALLOT_CAST_DIRECT: 'VOTING.BALLOT_CAST_DIRECT',
  BALLOT_CAST_PROXY: 'VOTING.BALLOT_CAST_PROXY',
  VOTE_CLOSED: 'VOTING.VOTE_CLOSED',
  VOTE_RESULTS_COMPUTED: 'VOTING.VOTE_RESULTS_COMPUTED',
} as const;

export type VotingEventType = (typeof VotingEventType)[keyof typeof VotingEventType];
